<a href="https://colab.research.google.com/github/Eduardo681/datascienceprojects/blob/main/RH.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **RH**

Importação de dependencias:
- Base de dados: https://www.kaggle.com/pavansubhasht/ibm-hr-analytics-attrition-dataset
- Cálculo de salário: https://www.mom.gov.sg/employment-practices/salary/monthly-and-daily-salary e https://sprout.zendesk.com/hc/en-us/articles/360030922133-How-to-Calculate-for-the-Daily-Rate-from-Your-Monthly-Salary-
- Stock: https://www.moneyunder30.com/employee-stock-options#:~:text=Typically%20they%20are%20granted%20to,a%20specific%20period%20of%20time.


In [16]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [17]:
employee_df = pd.read_csv('/Human_Resources.csv')

In [18]:
employee_df.shape

(1470, 35)

In [ ]:
employee_df.head()

In [ ]:
employee_df.info()

In [ ]:
employee_df.describe()

# Vizualização de dados

In [22]:
employee_df['Attrition'] = employee_df['Attrition'].apply(lambda x:1 if x == 'Yes' else 0)
employee_df['OverTime'] = employee_df['OverTime'].apply(lambda x:1 if x == 'Yes' else 0)

In [ ]:
employee_df.head()

In [ ]:
sns.heatmap(employee_df.isnull());

In [ ]:
employee_df.hist(bins = 30, figsize=(20,20), color = 'r');

In [26]:
employee_df.drop(['EmployeeCount', 'StandardHours', 'Over18', 'EmployeeNumber'], axis=1, inplace=True)

In [ ]:
employee_df.head()

In [28]:
left_df = employee_df[employee_df['Attrition'] == 1]
stayed_df = employee_df[employee_df['Attrition'] == 0]

In [ ]:
print('Total = ', len(employee_df))
print('Número de funcionários que saíram da empresa = ', len(left_df))
print('Porcentagem de funcionários que saíram da empresa = ', len(left_df) / len(employee_df) * 100 )
print()
print('Número de funcionários que ficaram da empresa = ', len(stayed_df))
print('Porcentagem de funcionários que ficaram da empresa = ', len(stayed_df) / len(employee_df) * 100 )

In [ ]:
left_df.describe()

In [ ]:
stayed_df.describe()

In [ ]:
correlations = employee_df.corr()
f, ax = plt.subplots(figsize=(20, 20))
sns.heatmap(correlations, annot=True);

In [ ]:
plt.figure(figsize=[25,12])
sns.countplot(x = 'Age', hue='Attrition', data=employee_df);

In [ ]:
plt.figure(figsize=[20,20])
plt.subplot(411)
sns.countplot(x = 'JobRole', hue='Attrition', data=employee_df)
plt.subplot(412)
sns.countplot(x = 'MaritalStatus', hue='Attrition', data=employee_df)
plt.subplot(413)
sns.countplot(x = 'JobInvolvement', hue='Attrition', data=employee_df)
plt.subplot(414)
sns.countplot(x = 'JobLevel', hue='Attrition', data=employee_df);

In [ ]:
# KDE
plt.figure(figsize=(12,7))
sns.kdeplot(left_df['DistanceFromHome'], label='Funcionarios que saíram', shade=True, color='r');
sns.kdeplot(stayed_df['DistanceFromHome'], label='Funcionarios que ficaram', shade=True, color='b');

In [ ]:
plt.figure(figsize=(12,7))
sns.kdeplot(left_df['TotalWorkingYears'], label='Funcionarios que saíram', shade=True, color='r');
sns.kdeplot(stayed_df['TotalWorkingYears'], label='Funcionarios que ficaram', shade=True, color='b');

In [ ]:
plt.figure(figsize=(15,10))
sns.boxplot(x = 'MonthlyIncome', y='Gender', data=employee_df)

In [ ]:
plt.figure(figsize=(15,10))
sns.boxplot(x='MonthlyIncome', y='JobRole', data=employee_df);

# Bases de treinamento/teste e limpeza dos dados

In [ ]:
employee_df.head()

In [ ]:
X_cat = employee_df[['BusinessTravel', 'Department', 'EducationField', 'Gender', 'JobRole', 'MaritalStatus']]
X_cat

In [ ]:
from sklearn.preprocessing import OneHotEncoder
onehotencoder = OneHotEncoder()
X_cat = onehotencoder.fit_transform(X_cat).toarray()
X_cat = pd.DataFrame(X_cat)
X_cat

In [ ]:
X_numerical = employee_df[['Age', 'DailyRate', 'DistanceFromHome',	'Education', 'EnvironmentSatisfaction', 'HourlyRate', 'JobInvolvement',	'JobLevel',	'JobSatisfaction',	'MonthlyIncome',	'MonthlyRate',	'NumCompaniesWorked',	'OverTime',	'PercentSalaryHike', 'PerformanceRating',	'RelationshipSatisfaction',	'StockOptionLevel',	'TotalWorkingYears'	,'TrainingTimesLastYear'	, 'WorkLifeBalance',	'YearsAtCompany'	,'YearsInCurrentRole', 'YearsSinceLastPromotion',	'YearsWithCurrManager']]
X_numerical

In [ ]:
X_all = pd.concat([X_cat, X_numerical], axis=1)
X_all

In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X = scaler.fit_transform(X_all)
X

In [45]:
y = employee_df['Attrition']

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.25)
X_train.shape, y_train
X_test, y_test

# **Regresão Logistica**

In [47]:
from sklearn.linear_model import LogisticRegression

In [50]:
logistic = LogisticRegression()
logistic.fit(X_train, y_train)


LogisticRegression()

In [ ]:
y_pred = logistic.predict(X_test)
y_pred

In [52]:
from sklearn.metrics import accuracy_score

In [53]:
accuracy_score(y_test, y_pred)

0.8641304347826086

In [54]:
from sklearn.metrics import confusion_matrix

In [55]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[296,   6],
       [ 44,  22]])

In [ ]:
sns.heatmap(cm, annot=True)

In [ ]:
# Precision
20 / (20 + 10)

0.6666666666666666

In [ ]:
# Recall
20 / (20 + 28)

0.4166666666666667

In [76]:
from sklearn.metrics import precision_score, recall_score, f1_score, classification_report

In [ ]:
precision_score(y_test, y_pred)

0.6666666666666666

In [ ]:
recall_score(y_test, y_pred)

0.4166666666666667

In [ ]:
f1_score(y_test, y_pred, average="macro")

0.7275348764710468

In [ ]:
print(classification_report(y_test, y_pred))

# **Random Florest**

In [56]:
from sklearn.ensemble import RandomForestClassifier

In [57]:
forest = RandomForestClassifier()
forest.fit(X_train, y_train)

RandomForestClassifier()

In [58]:
y_pred = forest.predict(X_test)

In [ ]:
accuracy_score(y_test, y_pred)

In [ ]:
cm = confusion_matrix(y_pred, y_test)
cm

In [ ]:
sns.heatmap(cm, annot=True)

In [ ]:
print(classification_report(y_test, y_pred))

# **Redes neurais artificiais**

In [48]:
import tensorflow as tf

In [67]:
rede_neural = tf.keras.models.Sequential()
rede_neural.add(tf.keras.layers.Dense(units = 25, activation="relu", input_shape=(50,)))
rede_neural.add(tf.keras.layers.Dense(units = 25, activation="relu"))
rede_neural.add(tf.keras.layers.Dense(units = 25, activation="relu"))
rede_neural.add(tf.keras.layers.Dense(units = 1, activation="sigmoid"))

In [ ]:
rede_neural.summary()

In [69]:
rede_neural.compile(optimizer="Adam", loss="binary_crossentropy", metrics = ['accuracy'])

In [ ]:
rede_neural.fit(X_train, y_train, epochs=200)

In [ ]:
y_pred = rede_neural.predict(X_test)
y_pred

In [ ]:
y_pred = (y_pred >= 0.5)
y_pred

In [73]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[293,  15],
       [ 29,  31]])

In [ ]:
sns.heatmap(cm, annot=True)

In [ ]:
print(classification_report(y_test, y_pred))

**Salvar o classificador**

In [78]:
import pickle

In [79]:
with open ('var_model.pkl', 'wb') as f:
  pickle.dump([scaler, onehotencoder,logistic], f)

In [88]:
with open('var_model.pkl', 'rb') as f:
  min_max, encoder, model = pickle.load(f)

In [89]:
min_max, encoder, model

(MinMaxScaler(), OneHotEncoder(), LogisticRegression())

In [90]:
X_novo = employee_df.iloc[0:1]
X_novo

Age  Attrition  ... YearsSinceLastPromotion  YearsWithCurrManager
0   41          1  ...                       0                     5

[1 rows x 31 columns]

In [91]:
X_cat_novo = X_novo[['BusinessTravel', 'Department', 'EducationField', 'Gender', 'JobRole', 'MaritalStatus']]

In [ ]:
X_cat_novo = encoder.transform(X_cat_novo).toarray()
X_cat_novo

In [93]:
X_cat_novo = pd.DataFrame(X_cat_novo)
X_cat_novo

0    1    2    3    4    5    6   ...   19   20   21   22   23   24   25
0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  ...  0.0  0.0  1.0  0.0  0.0  0.0  1.0

[1 rows x 26 columns]

In [ ]:
X_numerical_novo = X_novo[['Age', 'DailyRate', 'DistanceFromHome',	'Education', 'EnvironmentSatisfaction', 'HourlyRate', 'JobInvolvement',	'JobLevel',	'JobSatisfaction',	'MonthlyIncome',	'MonthlyRate',	'NumCompaniesWorked',	'OverTime',	'PercentSalaryHike', 'PerformanceRating',	'RelationshipSatisfaction',	'StockOptionLevel',	'TotalWorkingYears'	,'TrainingTimesLastYear'	, 'WorkLifeBalance',	'YearsAtCompany'	,'YearsInCurrentRole', 'YearsSinceLastPromotion',	'YearsWithCurrManager']]
X_numerical_novo

In [96]:
X_all_novo = pd.concat([X_cat_novo, X_numerical_novo], axis=1)
X_all_novo

0    1  ...  YearsSinceLastPromotion  YearsWithCurrManager
0  0.0  0.0  ...                        0                     5

[1 rows x 50 columns]

In [ ]:
X_novo = min_max.transform(X_all_novo)
X_novo

In [98]:
model.predict(X_novo)

array([1])

In [99]:
model.predict_proba(X_novo)

array([[0.36697974, 0.63302026]])

In [100]:
model.classes_

array([0, 1])